# Generated by Django 5.1.4 on 2025-02-03 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='분반 이름')),
            ],
            options={
                'verbose_name': '분반',
                'verbose_name_plural': '분반들',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='시험 이름')),
                ('date', models.DateField(blank=True, null=True, verbose_name='시험 실시 날짜')),
                ('average', models.FloatField(blank=True, null=True, verbose_name='시험 평균')),
                ('top_scores', models.CharField(blank=True, max_length=200, null=True, verbose_name='상위 점수 3개')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='students.classgroup', verbose_name='시험 실시 분반')),
            ],
            options={
                'verbose_name': '시험',
                'verbose_name_plural': '시험들',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='학생 이름')),
                ('school', models.CharField(max_length=100, verbose_name='출신 학교')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.classgroup', verbose_name='분반')),
            ],
            options={
                'verbose_name': '학생',
                'verbose_name_plural': '학생들',
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('응시', '응시'), ('결석', '결석'), ('녹화본', '녹화본'), ('조퇴', '조퇴'), ('라이브', '라이브'), ('미응시', '미응시')], max_length=10, verbose_name='응시 상태')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='시험 점수')),
                ('field1', models.FloatField(blank=True, null=True, verbose_name='분야별 점수 - Field1')),
                ('field2', models.FloatField(blank=True, null=True, verbose_name='분야별 점수 - Field2')),
                ('field3', models.FloatField(blank=True, null=True, verbose_name='분야별 점수 - Field3')),
                ('field4', models.FloatField(blank=True, null=True, verbose_name='분야별 점수 - Field4')),
                ('field5', models.FloatField(blank=True, null=True, verbose_name='분야별 점수 - Field5')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.exam', verbose_name='시험')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '시험 결과',
                'verbose_name_plural': '시험 결과들',
            },
        ),
    ]
