# Generated by Django 5.1.4 on 2025-02-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='석차'),
        ),
    ]
