# Generated by Django 5.1.4 on 2025-02-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_examresult_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='status',
            field=models.CharField(choices=[('응시', '응시'), ('결석', '결석'), ('녹화본', '녹화본'), ('조퇴', '조퇴'), ('라이브', '라이브'), ('미응시', '미응시'), ('내신', '내신')], max_length=10, verbose_name='응시 상태'),
        ),
    ]
