# Generated by Django 5.1.4 on 2025-02-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_examresult_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='score',
        ),
        migrations.AddField(
            model_name='examresult',
            name='exam_date',
            field=models.DateField(blank=True, null=True, verbose_name='시험 실시 날짜'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='max_score',
            field=models.FloatField(blank=True, null=True, verbose_name='만점'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='total_score',
            field=models.FloatField(blank=True, null=True, verbose_name='총점'),
        ),
    ]
