# Generated by Django 5.1.4 on 2025-02-09 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_examresult_report_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='분야 이름')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_definitions', to='students.classgroup', verbose_name='분반')),
            ],
            options={
                'verbose_name': '분야 정의',
                'verbose_name_plural': '분야 정의들',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExamFieldResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='분야 점수')),
                ('exam_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_results', to='students.examresult', verbose_name='시험 결과')),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.fielddefinition', verbose_name='분야')),
            ],
            options={
                'verbose_name': '시험 분야 결과',
                'verbose_name_plural': '시험 분야 결과들',
                'unique_together': {('exam_result', 'field_definition')},
            },
        ),
    ]
