# Generated by Django 5.1.4 on 2025-02-11 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_examresult_field1_examresult_field1_definition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='전화번호')),
                ('students', models.ManyToManyField(related_name='parents', to='students.student', verbose_name='자녀 목록')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='학부모 계정')),
            ],
            options={
                'verbose_name': '학부모',
                'verbose_name_plural': '학부모들',
            },
        ),
    ]
