# Generated by Django 5.1.4 on 2025-02-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fielddefinition',
            options={'verbose_name': '시험 분야', 'verbose_name_plural': '시험 분야들'},
        ),
        migrations.RemoveField(
            model_name='fielddefinition',
            name='order',
        ),
        migrations.AlterField(
            model_name='fielddefinition',
            name='name',
            field=models.CharField(max_length=50, verbose_name='분야 이름'),
        ),
    ]
