# Generated by Django 5.1.4 on 2025-02-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_fielddefinition_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='average',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='시험 평균'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='field1',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='분야별 점수 - Field1'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='field2',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='분야별 점수 - Field2'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='field3',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='분야별 점수 - Field3'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='field4',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='분야별 점수 - Field4'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='field5',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='분야별 점수 - Field5'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='max_score',
            field=models.FloatField(blank=True, default=100, null=True, verbose_name='만점'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='rank',
            field=models.IntegerField(blank=True, default=-1, null=True, verbose_name='석차'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='total_score',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='총점'),
        ),
    ]
