# Generated by Django 5.1.4 on 2025-02-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_exam_average_alter_examresult_field1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='avg_field1',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='분야1 평균'),
        ),
        migrations.AddField(
            model_name='exam',
            name='avg_field2',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='분야2 평균'),
        ),
        migrations.AddField(
            model_name='exam',
            name='avg_field3',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='분야3 평균'),
        ),
        migrations.AddField(
            model_name='exam',
            name='avg_field4',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='분야4 평균'),
        ),
        migrations.AddField(
            model_name='exam',
            name='avg_field5',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='분야5 평균'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='average',
            field=models.FloatField(blank=True, null=True, verbose_name='시험 평균'),
        ),
    ]
