# Generated by Django 5.1.4 on 2025-02-17 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_assignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-date'], 'verbose_name': '과제', 'verbose_name_plural': '과제 목록'},
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='completion_rate',
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_rate', models.FloatField(default=0.0, help_text='0.0 ~ 1.0 사이 (예: 0.7 => 70% 이행)', verbose_name='이행률')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students.assignment', verbose_name='과제')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='students.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '과제 이행 정보',
                'verbose_name_plural': '과제 이행 정보들',
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
