# Generated by Django 5.1.4 on 2025-02-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='completion_rate',
            field=models.FloatField(default=0.0, help_text='0 ~ 100 사이 (예: 70 => 70% 이행)', verbose_name='이행률'),
        ),
    ]
