# Generated by Django 5.1.4 on 2025-02-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_alter_assignmentsubmission_completion_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='title',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='completion_rate',
        ),
        migrations.AddField(
            model_name='assignment',
            name='daily_comment',
            field=models.TextField(blank=True, verbose_name='일일 코멘트'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='task1_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='과제1 이름'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='task2_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='과제2 이름'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='task3_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='과제3 이름'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='task4_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='과제4 이름'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='task5_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='과제5 이름'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='completion_rate1',
            field=models.FloatField(default=0.0, verbose_name='과제1 이행률'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='completion_rate2',
            field=models.FloatField(default=0.0, verbose_name='과제2 이행률'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='completion_rate3',
            field=models.FloatField(default=0.0, verbose_name='과제3 이행률'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='completion_rate4',
            field=models.FloatField(default=0.0, verbose_name='과제4 이행률'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='completion_rate5',
            field=models.FloatField(default=0.0, verbose_name='과제5 이행률'),
        ),
    ]
