# Generated by Django 5.1.4 on 2025-02-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_remove_assignment_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='daily_comment',
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='daily_comment',
            field=models.TextField(blank=True, verbose_name='일일 코멘트'),
        ),
    ]
