# Generated by Django 5.1.4 on 2025-03-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_remove_assignment_daily_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='students.parent', verbose_name='학부모 목록'),
        ),
    ]
